version: '3.8'

services:
  clientes:
    image: sua_imagem_clientes
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db_clientes:5432/clientes
    depends_on:
      - db_clientes

  entregas:
    image: sua_imagem_entregas
    ports:
      - "8084:8084"
    environment:
      - DB_URL=jdbc:postgresql://db_entregas:5432/entregas
    depends_on:
      - db_entregas

  produtos:
    image: sua_imagem_produtos
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db_produtos:5432/produtos
    depends_on:
      - db_produtos

  pedidos:
    image: sua_imagem_pedidos
    ports:
      - "8082:8082"
    environment:
      - CLIENTES_SERVICE_URL=http://clientes:8080
      - ENTREGAS_SERVICE_URL=http://entregas:8084
      - PRODUTOS_SERVICE_URL=http://produtos:8081
    depends_on:
      - clientes
      - entregas
      - produtos

  db_clientes:
    image: postgres
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  db_entregas:
    image: postgres
    environment:
      POSTGRES_DB: entregas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  db_produtos:
    image: postgres
    environment:
      POSTGRES_DB: produtos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

networks:
  default:
    driver: bridge
